enhancement:
- changed-files:
  - any-glob-to-any-file: '**'

documentation:
- changed-files:
  - any-glob-to-any-file:
    - .codex/**
    - docs/**
    - guides/**

backend:
- all:
  - changed-files:
    - any-glob-to-any-file: 'backend/**'

char:
- all:
  - changed-files:
    - any-glob-to-any-file: 'backend/plugins/characters/**'

passive:
- all:
  - changed-files:
    - any-glob-to-any-file: 'backend/plugins/passives/**'

card:
- all:
  - changed-files:
    - any-glob-to-any-file: 'backend/plugins/cards/**'

relic:
- all:
  - changed-files:
    - any-glob-to-any-file: 'backend/plugins/relics/**'

frontend:
- all:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**'

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
 - head-branch: ['^feature', 'feature']
